services:
  nap-web:
    build: 
      context: ../nap-web
    networks:
      - web_network
  nap-sparql:
    build:
      context: fuseki
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ENABLE_DATA_WRITE=false
      - ENABLE_UPDATE=false
      - ENABLE_SHACL=false
    volumes:
      - ../sparql_server/data:/databases
    networks:
      - web_network
networks:
  web_network:
    external: true
    name: web_network
